/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MujikaAbout: typeof import('./src/components/MujikaAbout.vue')['default']
    MujikaArchive: typeof import('./src/components/MujikaArchive.vue')['default']
    MujikaAside: typeof import('./src/components/MujikaAside.vue')['default']
    MujikaAuthorAvatar: typeof import('./src/components/MujikaAuthorAvatar.vue')['default']
    MujikaAuthorCard: typeof import('./src/components/MujikaAuthorCard.vue')['default']
    MujikaAuthorStatistic: typeof import('./src/components/MujikaAuthorStatistic.vue')['default']
    MujikaCard: typeof import('./src/components/MujikaCard.vue')['default']
    MujikaCategory: typeof import('./src/components/MujikaCategory.vue')['default']
    MujikaFooter: typeof import('./src/components/MujikaFooter.vue')['default']
    MujikaHeader: typeof import('./src/components/MujikaHeader.vue')['default']
    MujikaLogoCard: typeof import('./src/components/MujikaLogoCard.vue')['default']
    MujikaPagination: typeof import('./src/components/MujikaPagination.vue')['default']
    MujikaPostDetail: typeof import('./src/components/MujikaPostDetail.vue')['default']
    MujikaPostList: typeof import('./src/components/MujikaPostList.vue')['default']
    MujikaPostListItem: typeof import('./src/components/MujikaPostListItem.vue')['default']
    MujikaPostMeta: typeof import('./src/components/MujikaPostMeta.vue')['default']
    MujikaTag: typeof import('./src/components/MujikaTag.vue')['default']
    MujikaToc: typeof import('./src/components/MujikaToc.vue')['default']
    MujikaTocList: typeof import('./src/components/MujikaTocList.vue')['default']
    MujikaVerticalDivider: typeof import('./src/components/MujikaVerticalDivider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
